server:
  port: 8010
spring:
  application:
    name: course
  datasource:
    url: jdbc:mysql://localhost:3306/xuanke?serverTimezone=GMT
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.gloryroad.entity