server:
  port: 8010
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xuanke?serverTimezone=GMT
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.gloryroad.entity